import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Navbar from '../components/Navbar'
import Projects from '../components/Projects'
import SocialMedia from '../components/SocialMedia'
import Testimony from '../components/Testimony'
import Volunteer from '../components/Volunteer'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description"  content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Testimony/>
      <About/>
      <SocialMedia/>
      <Projects/>
      <Volunteer/>
     </div>
  )
}
